# Generated by Django 4.0.4 on 2022-04-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='birth_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
