# Generated by Django 4.0.4 on 2022-04-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0002_attendee_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendee',
            options={'verbose_name': 'Asistente', 'verbose_name_plural': 'Asistentes'},
        ),
        migrations.AddField(
            model_name='attendee',
            name='code',
            field=models.CharField(default=321321, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
