# Generated by Django 4.0.4 on 2022-04-18 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        ('attendee', '0003_alter_attendee_options_attendee_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='attendees', to='event.event'),
        ),
    ]
