# Generated by Django 4.0.4 on 2022-04-18 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=datetime.datetime(2022, 4, 18, 23, 18, 20, 232354))),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
