-- Listar los nros. De facturas que tienen el articulo 4000 o el articulo 4010 o el articulo 4020
SELECT DISTINCT FACTURA.NROFACTURA from FACTURA 
    INNER JOIN DETALLE ON  FACTURA.NROFACTURA = DETALLE.NROFACTURA
    INNER JOIN ARTICULO ON DETALLE.ARTICULO = ARTICULO.NROARTIC
    WHERE ARTICULO.NROARTIC IN (4000, 4010, 4020);
    -- WHERE ARTICULO.NROARTIC = 4000 or ARTICULO.NROARTIC =  4010 or ARTICULO.NROARTIC =   4020

SELECT DISTINCT DETALLE.NROFACTURA from DETALLE 
    INNER JOIN ARTICULO ON DETALLE.ARTICULO = ARTICULO.NROARTIC
    WHERE ARTICULO.NROARTIC IN (4000, 4010, 4020);